
#define BOREAL_VERSION_MAJOR		1
#define BOREAL_VERSION_MINOR		0
#define BOREAL_VERSION_BUILD		1

#define BOREAL_COPYRIGHT "© Boreal Inspection Inc. 2001-2011"

#define BOREAL_FULL_FILE_VERSION_STR	"1.0.1"

